# Generated by Django 5.2 on 2025-05-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_provider_images/')),
                ('description', models.TextField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.serviceprovider')),
            ],
        ),
    ]
