# Generated by Django 5.2 on 2025-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
