# Generated by Django 5.2 on 2025-05-22 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 17, 37, 10, 138995, tzinfo=datetime.timezone.utc)),
        ),
    ]
