# Generated by Django 5.2 on 2025-05-23 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 5, 21, 3, 286431, tzinfo=datetime.timezone.utc)),
        ),
    ]
